name: bis
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  loading_animation_widget: ^1.2.0+3
  page_transition: ^2.0.9
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  flutter_launcher_icons: ^0.11.0
  firebase_messaging: ^14.1.1
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.0.2
  intl: ^0.17.0
  dotted_border: ^2.0.0+3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/school_logo.jpeg"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
